services:
  identity:
    build:
      context: ./TimeTracker.Identity/
      dockerfile: TimeTracker.Identity/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "59001:80"
  api:
    build:
      context: ./api/
      dockerfile: TimeTracker.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "59002:80"
