services:
  api:
    build:
      context: ./api/
      dockerfile: TimeTracker.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - IDENTITY_URL=http://identity/
    depends_on:
      - identity
    ports:
      - "59002:80"
  identity:
    build:
      context: ./TimeTracker.Identity/
      dockerfile: TimeTracker.Identity/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ISSUER_URI=http://identity
    ports:
      - "59001:80"
  web:
    depends_on:
      - identity
      - api
    build:
      context: ./web-client/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
